language: c
compiler: gcc
before_install:
  - sudo apt-get -y install check libsasl2-dev libsasl2-2
  - >
      if [ "x`uname -m`" = "xx86_64" ]; then
        wget http://mirror.anl.gov/pub/ubuntu/pool/main/c/cython/cython_0.20.1+git90-g0e6e38e-1ubuntu2_amd64.deb ;
        sudo dpkg -i cython_0.20.1+git90-g0e6e38e-1ubuntu2_amd64.deb ;
      else
        wget http://mirror.anl.gov/pub/ubuntu/pool/main/c/cython/cython_0.20.1+git90-g0e6e38e-1ubuntu2_i386.deb ;
        sudo dpkg -i cython_0.20.1+git90-g0e6e38e-1ubuntu2_i386.deb ;
      fi
  - wget https://protobuf.googlecode.com/svn/rc/protobuf-2.6.0.tar.gz
  - tar -xzf protobuf-2.6.0.tar.gz
  - ( cd protobuf-2.6.0 && ./configure --prefix=/usr && make && sudo make install )
  - wget https://github.com/protobuf-c/protobuf-c/releases/download/v1.1.0/protobuf-c-1.1.0.tar.gz
  - tar -xzf protobuf-c-1.1.0.tar.gz
  - ( cd protobuf-c-1.1.0 && ./configure && make && sudo make install )
  - ( [ ! -e /usr/bin/gmake ] && cd /usr/bin && sudo ln -s `which make` gmake )
# TODO:
# make test requires live HDFS cluster...
# For now, just compile everything.
script: >
  make all all-test
